<?php /* @var $this Fooman_GoogleAnalyticsPlus_Block_Universal */?>
<?php if ($this->shouldInclude()): ?>
    <?php $altUniversal = $this->getAlternativeUniversalAccount(); ?>
    <script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $this->getUniversalAccount(); ?>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '<?php echo $this->getUniversalAccount(); ?>');
    </script>
    <?php if($this->isSuccessPage() && $this->sendEcommerceTracking()):?>
        <?php $order = $this->_getOrder();?>
        <script>
            <?php
            $shipping = Mage::helper('googleanalyticsplus')->convert($order, 'shipping_amount', $order->getOrderCurrencyCode());
            $tax = Mage::helper('googleanalyticsplus')->convert($order, 'tax_amount', $order->getOrderCurrencyCode());
            $revenue =  Mage::helper('googleanalyticsplus')->convert($order, 'grand_total', $order->getOrderCurrencyCode());
            $revenue -= (($this->shouldExcludeShipping())? $shipping : 0);
            $revenue -= (($this->shouldExcludeTax())? $tax : 0);

            $transactionDetails = "{
            'transaction_id': '". $this->jsQuoteEscape($order->getIncrementId()) ."',
            'affiliation': '". $this->jsQuoteEscape(Mage::app()->getStore()->getName()) ."',
            'value': '". $revenue ."',
            'tax': '". $tax ."',
            'shipping': '". $shipping ."',
            'currency': '". Mage::helper('googleanalyticsplus')->getTrackingCurrency($order) ."',
            'items': [ ";

            foreach ($order->getAllVisibleItems() as $item) {
                $transactionDetails .=  "{
                'item_id': '" . $this->jsQuoteEscape($item->getSku()) . "',
                'item_name': '" . $this->jsQuoteEscape($item->getName()) . "',
                'affiliation': '" . $this->jsQuoteEscape(Mage::app()->getStore()->getName()) . "',
                'currency': '". Mage::helper('googleanalyticsplus')->getTrackingCurrency($order) ."',
                'item_category': '" . $this->jsQuoteEscape($this->getCategory($item)) . "',
                'price': '" . Mage::helper('googleanalyticsplus')->convert($item, 'price', $order->getOrderCurrencyCode()) . "',
                'quantity': '" . (int)$item->getQtyOrdered() . "'
                },";
            };

            $transactionDetails .=  " ]
            }";
            ?>
            gtag("event", "purchase",<?php echo $transactionDetails?>);
        </script>
    <?php endif; ?>
<?php endif; ?>
